services:
  mathesar:
    image: mathesar/mathesar-prod:latest
    container_name: sendthenoise-mathesar
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Use the same postgres database for Mathesar's internal storage
      MATHESAR_DATABASES: "(sendthenoise|postgresql://postgres:postgres@postgres:5432/sendthenoise)"
      SECRET_KEY: changeme-in-production
      DJANGO_SETTINGS_MODULE: config.settings.production
      ALLOWED_HOSTS: "*"
      # Internal Mathesar database (uses same postgres instance)
      POSTGRES_DB: mathesar_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - sendthenoise-net
